// أسماء البلديات الموريتانية بالعربية — مطابقة للقائمة الرسمية
export const COMMUNE_NAMES_AR = {
  "Amourj": "آمرج",
  "Oum Echeich": "أم اعشيش",
  "Bougadoum": "بوݣادوم",
  "Djigui": "جيكي",
  "Legdour": "لكدور",
  "Basseknou": "باسكنو",
  "El Megve": "المكفه",
  "Vessale": "فصاله",
  "Dhar": "اظهر",
  "Djiguenni": "جيكني",
  "El Mabrouk 1": "المبروك",
  "Feirenni": "افيرني",
  "Beneamane": "بنعمان",
  "Aoueinat Ez Bel": "اعوينات ازبل",
  "Ghlig Ehel Beye": "اغليݣ اهل بي",
  "Kasr El Barke": "قصر البركة",
  "Néma": "النعمه",
  "Achemime": "اشميم",
  "Jreif": "اجريف",
  "Bangou": "بنݣو",
  "Hassi Etile": "حاسي اتيل",
  "Oum Avnadech": "ام آفنادش",
  "El Mabrouk 2": "المبروك",
  "Beribavat": "بريبفات",
  "Noual": "نوال",
  "Agoueinit": "آݣوينت",
  "Oualata": "ولاته",
  "Elbatene": "الباطن",
  "Tembedgha": "تمبدغة",
  "Touil 1": "اطويل",
  "Koumbi Saleh": "كومبي صالح",
  "Bousteile": "بوسطيل",
  "Hassi M'Hadi": "حاسي امهادي",
  "Nbeikett Lehwache": "امبيكت لحواش",
  "Adel Bagrou": "عدل بݣرو",
  "Elmessgoul": "المصكول",
  "Sivane": "السيفان",
  "Aïoun El Atrouss": "لعيون",
  "N'Savenni": "انصفني",
  "Doueirare": "ادويرارة",
  "Ten Hamadi": "تنحماد",
  "Egjert": "اݣجرت",
  "Oum Lahyadh": "ام لحياظ",
  "Koubenni": "كوبني",
  "Hassi Ehel Ahmed Bechne": "حاسي اهل احمد بشنه",
  "Timzine": "تيمزين",
  "Leghlig": "لغليݣ",
  "Gougui Zemmal": "ݣوݣي الزمال",
  "Modibougou": "مودي بوݣو",
  "Voullaniya": "الفولانية",
  "Tamchekett": "تامشكط",
  "El Mabrouk 3": "المبروك",
  "Radhi": "الراظي",
  "Guetae-Teidoume": "ݣطع التيدومة",
  "Sava": "الصفا",
  "Tintan": "الطينطان",
  "Hassi Abdallah": "حاسي عبد الله",
  "Aweinat Thalle": "اعوينات الطل",
  "Aïn Varbe": "عين فربة",
  "Egharghar": "اغرغار",
  "Dev-a": " الدفعه",
  "Touil 2": "اطويل",
  "Baghdad": "بغداد",
  "Sett": "السط",
  "Lehreijat": "لحريجات",
  "Barkeiwel": "باركيول",
  "Gueller": "ݣلير",
  "Lebheir": "لبحير",
  "Laweissi": "لعويسي",
  "Daghveg": "دغفك",
  "El Ghabra": "الغبرة",
  "R'Dheidhie": "ارظيظيع",
  "Bou Lahrath": "بو لحراث",
  "Boumdeid": "بومديد",
  "Hseiy Tin": "حاسي الطين",
  "Lavtah": "لفطح",
  "Guerou": "ݣرو",
  "Oudeiy Jrid": "اودي اجريد",
  "El Ghaira": "الغايرة",
  "Kamour": "كامور",
  "Kankoussa": "كنكوصة",
  "Sani": "ساني",
  "Blajmil": "بلاجميل",
  "Tenaha": "تناها",
  "Hamed": "هامد",
  "Kiffa": "كيفه",
  "Nouamlein": "النواملين",
  "Aghorat": "اغورط",
  "El Melgue": "الملݣة",
  "Kouroudjel": "كورودجل",
  "Legrane": "لݣران",
  "Kaedi": "كيهيدي",
  "Néré Walo": "نيري والو",
  "Djewol": "جول",
  "Toghomadi": "تكمادي",
  "Tifondé Civé": "تيفوند سيفي",
  "Maghama": "مغامة",
  "Doo": "ضو",
  "Dolol Civé": "دول سيفه",
  "Beilouguet Litame": "بيلݣت ليتام",
  "Vrea Litame": "فرع ليتامة",
  "Toulel": "تولل",
  "Sagné": "صنيه",
  "Wali Djantang": "والي جنتن",
  "M'Boud": "امبود",
  "Tikobra": "تيكوبرا",
  "Terenguel Ehel Moulaye Ely": "تارݣنت أهل مولاي اعلي",
  "N'Djadjbenni Gandéga": "انجاد بني ݣان دݣا",
  "Edebaye Ehel Guelaye": "ادباي اهل ݣلاي",
  "Voum Legleite": "فم لݣليت",
  "Chelkhet Tiyab": "شلخت التياب",
  "Lahrach": "لحرش",
  "Souve": "سوفه",
  "Mounguel": "مونݣل",
  "Bathet Moït": "بطحت ميت",
  "Bokhol": "بوݣل",
  "Melzem Teichet": "ملزم تيشط",
  "Azgueilem Tiyab": "ازݣيلم لتياب",
  "Lexeiba 1": "لكصيبة",
  "Betengal": "بتنغال",
  "Talhaye": "تالهاي",
  "Ganki": "ݣانكي",
  "Aleg": "الاك",
  "Chegar": "شݣار",
  "Bouhdida": "بوحديدة",
  "Aghchourguit": "اغشورݣيت",
  "Bababé": "بابابي",
  "El Verae": "الفرع",
  "Aéré M'Bar": "ايره امبار",
  "Boghé": "بوݣي",
  "Dar El Aviye": "دار العافية",
  "Dar El Barke": "دار البركة",
  "Ould Biram": "ول بيرم",
  "Magtalahjar": "مقطع لحجار",
  "Sangrave": "صنݣرافة",
  "Djonabe": "جونابه",
  "Ouad Emmour": "واد آمور",
  "M'Bagne": "امبان",
  "Niabina": "النابينا",
  "Edebaye El Hejjaj": "ادباي الحجاج",
  "Bagodine": "باݣودين",
  "Maal": "مال",
  "Roumed": "رومده",
  "Elwad Lebiadh": "الواد لبيضة",
  "Bourat": "بورات",
  "Djelwar": "جلوار",
  "Boutilimit": "بوتلميت",
  "Elb Adress": "علب آدرس",
  "Ajoueir": "آجوير",
  "N'Teichet": "انتيشط",
  "Nebaghiye": "النباغية",
  "Tenghadej": "تنغدج",
  "El Mouyessar": "الميسر",
  "Keurmacen": "كرمسين",
  "N'Diago": "انجاݣو",
  "M'Balal": "امبلل",
  "Mederdra": "المذرذرة",
  "Beir Taouress": "ابير التورس",
  "Taguilalet": "التاݣيلالت",
  "El Khat": "الخط",
  "Tiguent (El Jedide)": "تݣند",
  "Ouad Naga": "واد الناقة",
  "Aouleiygat": "آوليݣات",
  "El Ariye": "العريه",
  "R'Kiz": "اركيز",
  "Boutalhaye": "بوطلحايه",
  "Bareine": "برينه",
  "Rosso": "روصو",
  "Jedrel Mouhguen": "جدر المحݣن",
  "Teikane": "التكان",
  "Chemame": "شمامة",
  "Teichteyat": "تيشتيات",
  "Lexelbe 2": "لكصيبة",
  "Aoujeft": "أوجفت",
  "Maeden": "المعدن",
  "N'Teirguent": "انتيرݣنت",
  "El Medah": "المداح",
  "Atar": "أطار",
  "Aïn Ehel Taya": "عين اهل الطايع",
  "Tawaz": "الطواز",
  "Choum": "شوم",
  "Chinguitti": "شنقيط",
  "Aïn Savra": "العين الصفرة",
  "Ouadane": "وادان",
  "Nouadhibou": "النواذيبو",
  "Boulenouar": "بولنوار",
  "Inal": "انال",
  "Chami": "الشامي",
  "Tmeimichat": "اتميميشات",
  "Nouamghar": "النوامغار",
  "Moudjeria": "المجرية",
  "N'Beike": "انبيكة",
  "Soudoud": "السدود",
  "Tichit": "تيشيت",
  "Lekhcheb": "لخشب",
  "Tidjikdja": "تجكجة",
  "El Wahat": "الواحات (الرشيد)",
  "Tensigh": "التنسيغ",
  "Boubacar Ben Amer": "بوبكر بن عامر",
  "Lehsira": "لحصيرة",
  "Ould Yengé": "ولد ينجه",
  "Leebelli": "لعبلي",
  "Tektake": "التكتاكة",
  "Davoue": "دافور",
  "Bouanz": "بو عنز",
  "Lehraj": "لحرج",
  "Leaweinat": "لعوينات",
  "Sélibabi": "سيليبابي",
  "Ould M'Bonny": "ولد امبوني",
  "Tachout": "التاشوط",
  "Hassi Chegar": "حاسي شݣار",
  "Ghabou": "غابو",
  "Chleikha": "شليخة",
  "Diogountou": "ديوجونتو",
  "Bayediam": "بايديم",
  "Gouraye": "ݣوري",
  "Soufi": "صوفي",
  "Wompou": "ومبو",
  "Agoueinitt": "آݣوينت",
  "Ejar": "اجار",
  "Sagne Dieri": "صني جيري",
  "Arr": "عر",
  "Birmoughrein": "بير ام اݣرين",
  "F'Deirick": "افديرك",
  "Zoueirat": "ازويرات",
  "Akjoujt": "اكجوجت",
  "Bennechab": "بنشاب",
  "Mheijrat": "مهيجرات",
  "Ksar": "لكصر",
  "Tefragh Zeina": "تفرغ زينة",
  "Sebkha": "السبخة",
  "Teyaret": "تيارت",
  "Dar Naim": "دار النعيم",
  "Toujounine": "توجنين",
  "El Mina": "الميناء",
  "Arafat": "عرفات",
  "Riyad": "الرياض"
};

// يرجع الاسم العربي للبلدية إن وُجد، وإلا الاسم كما هو (لتفادي ظهور أسماء لاتينية)
export function toArabicCommune(name) {
  if (!name) return name;
  return COMMUNE_NAMES_AR[name] || name;
}
