import {
  normalizeMauritaniaMoughataaName,
  normalizeMauritaniaWilayaName,
} from './mauritaniaPlaceNames';
import { COMMUNE_NAMES_AR } from './mauritaniaCommuneNamesAr';

// الاسم العربي للبلدية إن توفّر، وإلا الاسم اللاتيني الأصلي
const arName = (commune) => COMMUNE_NAMES_AR[commune.city] || commune.name || commune.city;

export const mauritaniaCommunesList = [
  {
    "city": "Amourj",
    "name": "Amourj",
    "lat": 16.081,
    "lon": -7.234,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Amourj",
    "id": "MR01101",
    "source": "open-admin-data"
  },
  {
    "city": "Oum Echeich",
    "name": "Oum Echeich",
    "lat": 15.677,
    "lon": -7.554,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Amourj",
    "id": "MR01102",
    "source": "open-admin-data"
  },
  {
    "city": "Bougadoum",
    "name": "Bougadoum",
    "lat": 15.835,
    "lon": -7.23,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Amourj",
    "id": "MR01103",
    "source": "open-admin-data"
  },
  {
    "city": "Djigui",
    "name": "Djigui",
    "lat": 15.672,
    "lon": -7.2,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Amourj",
    "id": "MR01104",
    "source": "open-admin-data"
  },
  {
    "city": "Legdour",
    "name": "Legdour",
    "lat": 15.866,
    "lon": -7.539,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Amourj",
    "id": "MR01105",
    "source": "open-admin-data"
  },
  {
    "city": "Basseknou",
    "name": "Basseknou",
    "lat": 15.863,
    "lon": -5.945,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Bassiknou",
    "id": "MR01106",
    "source": "open-admin-data"
  },
  {
    "city": "El Megve",
    "name": "El Megve",
    "lat": 16.162,
    "lon": -5.563,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Bassiknou",
    "id": "MR01107",
    "source": "open-admin-data"
  },
  {
    "city": "Vessale",
    "name": "Vessale",
    "lat": 15.669,
    "lon": -5.855,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Bassiknou",
    "id": "MR01108",
    "source": "open-admin-data"
  },
  {
    "city": "Dhar",
    "name": "Dhar",
    "lat": 16.171,
    "lon": -6.279,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Bassiknou",
    "id": "MR01109",
    "source": "open-admin-data"
  },
  {
    "city": "Djiguenni",
    "name": "Djiguenni",
    "lat": 15.736,
    "lon": -8.667,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Djiguenni",
    "id": "MR01110",
    "source": "open-admin-data"
  },
  {
    "city": "El Mabrouk 1",
    "name": "El Mabrouk 1",
    "lat": 15.671,
    "lon": -8.501,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Djiguenni",
    "id": "MR01111",
    "source": "open-admin-data"
  },
  {
    "city": "Feirenni",
    "name": "Feirenni",
    "lat": 15.566,
    "lon": -8.837,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Djiguenni",
    "id": "MR01112",
    "source": "open-admin-data"
  },
  {
    "city": "Beneamane",
    "name": "Beneamane",
    "lat": 15.923,
    "lon": -8.847,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Djiguenni",
    "id": "MR01113",
    "source": "open-admin-data"
  },
  {
    "city": "Aoueinat Ez Bel",
    "name": "Aoueinat Ez Bel",
    "lat": 16.338,
    "lon": -8.763,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Djiguenni",
    "id": "MR01114",
    "source": "open-admin-data"
  },
  {
    "city": "Ghlig Ehel Beye",
    "name": "Ghlig Ehel Beye",
    "lat": 15.964,
    "lon": -8.602,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Djiguenni",
    "id": "MR01115",
    "source": "open-admin-data"
  },
  {
    "city": "Kasr El Barke",
    "name": "Kasr El Barke",
    "lat": 15.729,
    "lon": -8.829,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Djiguenni",
    "id": "MR01116",
    "source": "open-admin-data"
  },
  {
    "city": "Néma",
    "name": "Néma",
    "lat": 16.613,
    "lon": -7.267,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Néma",
    "id": "MR01117",
    "source": "open-admin-data"
  },
  {
    "city": "Achemime",
    "name": "Achemime",
    "lat": 16.755,
    "lon": -7.128,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Néma",
    "id": "MR01118",
    "source": "open-admin-data"
  },
  {
    "city": "Jreif",
    "name": "Jreif",
    "lat": 16.428,
    "lon": -7.171,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Néma",
    "id": "MR01119",
    "source": "open-admin-data"
  },
  {
    "city": "Bangou",
    "name": "Bangou",
    "lat": 16.291,
    "lon": -6.983,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Néma",
    "id": "MR01120",
    "source": "open-admin-data"
  },
  {
    "city": "Hassi Etile",
    "name": "Hassi Etile",
    "lat": 16.172,
    "lon": -7.276,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Néma",
    "id": "MR01121",
    "source": "open-admin-data"
  },
  {
    "city": "Oum Avnadech",
    "name": "Oum Avnadech",
    "lat": 16.08,
    "lon": -7.606,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Néma",
    "id": "MR01122",
    "source": "open-admin-data"
  },
  {
    "city": "El Mabrouk 2",
    "name": "El Mabrouk 2",
    "lat": 16.468,
    "lon": -7.339,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Néma",
    "id": "MR01123",
    "source": "open-admin-data"
  },
  {
    "city": "Beribavat",
    "name": "Beribavat",
    "lat": 16.436,
    "lon": -7.572,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Néma",
    "id": "MR01124",
    "source": "open-admin-data"
  },
  {
    "city": "Noual",
    "name": "Noual",
    "lat": 16.512,
    "lon": -7.751,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Néma",
    "id": "MR01125",
    "source": "open-admin-data"
  },
  {
    "city": "Agoueinit",
    "name": "Agoueinit",
    "lat": 16.648,
    "lon": -7.453,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Néma",
    "id": "MR01126",
    "source": "open-admin-data"
  },
  {
    "city": "Oualata",
    "name": "Oualata",
    "lat": 20.092,
    "lon": -6.877,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Oualata",
    "id": "MR01127",
    "source": "open-admin-data"
  },
  {
    "city": "Elbatene",
    "name": "Elbatene",
    "lat": 17.177,
    "lon": -7.748,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Oualata",
    "id": "MR01128",
    "source": "open-admin-data"
  },
  {
    "city": "Tembedgha",
    "name": "Tembedgha",
    "lat": 16.24,
    "lon": -8.164,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Timbédra",
    "id": "MR01129",
    "source": "open-admin-data"
  },
  {
    "city": "Touil 1",
    "name": "Touil 1",
    "lat": 16.579,
    "lon": -8.293,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Timbédra",
    "id": "MR01130",
    "source": "open-admin-data"
  },
  {
    "city": "Koumbi Saleh",
    "name": "Koumbi Saleh",
    "lat": 15.895,
    "lon": -7.967,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Timbédra",
    "id": "MR01131",
    "source": "open-admin-data"
  },
  {
    "city": "Bousteile",
    "name": "Bousteile",
    "lat": 15.619,
    "lon": -8.161,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Timbédra",
    "id": "MR01132",
    "source": "open-admin-data"
  },
  {
    "city": "Hassi M'Hadi",
    "name": "Hassi M'Hadi",
    "lat": 15.991,
    "lon": -8.315,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Timbédra",
    "id": "MR01133",
    "source": "open-admin-data"
  },
  {
    "city": "Nbeikett Lehwache",
    "name": "Nbeikett Lehwache",
    "lat": 18.131,
    "lon": -6.149,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "N'Beiket Lehwach",
    "id": "MR01134",
    "source": "open-admin-data"
  },
  {
    "city": "Adel Bagrou",
    "name": "Adel Bagrou",
    "lat": 15.543,
    "lon": -7.009,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Adel Bagrou",
    "id": "MR01135",
    "source": "open-admin-data"
  },
  {
    "city": "Elmessgoul",
    "name": "Elmessgoul",
    "lat": 15.874,
    "lon": -6.474,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Adel Bagrou",
    "id": "MR01136",
    "source": "open-admin-data"
  },
  {
    "city": "Sivane",
    "name": "Sivane",
    "lat": 15.84,
    "lon": -6.882,
    "type": "بلدية",
    "wilaya": "الحوض الشرقي",
    "moughataa": "Adel Bagrou",
    "id": "MR01137",
    "source": "open-admin-data"
  },
  {
    "city": "Aïoun El Atrouss",
    "name": "Aïoun El Atrouss",
    "lat": 16.693,
    "lon": -9.639,
    "type": "بلدية",
    "wilaya": "الحوض الغربي",
    "moughataa": "Aïoun",
    "id": "MR01138",
    "source": "open-admin-data"
  },
  {
    "city": "N'Savenni",
    "name": "N'Savenni",
    "lat": 17.044,
    "lon": -9.719,
    "type": "بلدية",
    "wilaya": "الحوض الغربي",
    "moughataa": "Aïoun",
    "id": "MR01139",
    "source": "open-admin-data"
  },
  {
    "city": "Doueirare",
    "name": "Doueirare",
    "lat": 16.701,
    "lon": -9.88,
    "type": "بلدية",
    "wilaya": "الحوض الغربي",
    "moughataa": "Aïoun",
    "id": "MR01140",
    "source": "open-admin-data"
  },
  {
    "city": "Ten Hamadi",
    "name": "Ten Hamadi",
    "lat": 16.433,
    "lon": -9.844,
    "type": "بلدية",
    "wilaya": "الحوض الغربي",
    "moughataa": "Aïoun",
    "id": "MR01141",
    "source": "open-admin-data"
  },
  {
    "city": "Beneamane",
    "name": "Beneamane",
    "lat": 16.404,
    "lon": -9.585,
    "type": "بلدية",
    "wilaya": "الحوض الغربي",
    "moughataa": "Aïoun",
    "id": "MR01142",
    "source": "open-admin-data"
  },
  {
    "city": "Egjert",
    "name": "Egjert",
    "lat": 17.053,
    "lon": -9.287,
    "type": "بلدية",
    "wilaya": "الحوض الغربي",
    "moughataa": "Aïoun",
    "id": "MR01143",
    "source": "open-admin-data"
  },
  {
    "city": "Oum Lahyadh",
    "name": "Oum Lahyadh",
    "lat": 16.846,
    "lon": -8.744,
    "type": "بلدية",
    "wilaya": "الحوض الغربي",
    "moughataa": "Aïoun",
    "id": "MR01144",
    "source": "open-admin-data"
  },
  {
    "city": "Koubenni",
    "name": "Koubenni",
    "lat": 15.808,
    "lon": -9.408,
    "type": "بلدية",
    "wilaya": "الحوض الغربي",
    "moughataa": "Kobeni",
    "id": "MR01145",
    "source": "open-admin-data"
  },
  {
    "city": "Hassi Ehel Ahmed Bechne",
    "name": "Hassi Ehel Ahmed Bechne",
    "lat": 15.985,
    "lon": -9.704,
    "type": "بلدية",
    "wilaya": "الحوض الغربي",
    "moughataa": "Kobeni",
    "id": "MR01146",
    "source": "open-admin-data"
  },
  {
    "city": "Timzine",
    "name": "Timzine",
    "lat": 16.209,
    "lon": -9.247,
    "type": "بلدية",
    "wilaya": "الحوض الغربي",
    "moughataa": "Kobeni",
    "id": "MR01147",
    "source": "open-admin-data"
  },
  {
    "city": "Leghlig",
    "name": "Leghlig",
    "lat": 15.779,
    "lon": -9.031,
    "type": "بلدية",
    "wilaya": "الحوض الغربي",
    "moughataa": "Kobeni",
    "id": "MR01148",
    "source": "open-admin-data"
  },
  {
    "city": "Gougui Zemmal",
    "name": "Gougui Zemmal",
    "lat": 15.684,
    "lon": -9.331,
    "type": "بلدية",
    "wilaya": "الحوض الغربي",
    "moughataa": "Kobeni",
    "id": "MR01149",
    "source": "open-admin-data"
  },
  {
    "city": "Modibougou",
    "name": "Modibougou",
    "lat": 15.664,
    "lon": -9.526,
    "type": "بلدية",
    "wilaya": "الحوض الغربي",
    "moughataa": "Kobeni",
    "id": "MR01150",
    "source": "open-admin-data"
  },
  {
    "city": "Voullaniya",
    "name": "Voullaniya",
    "lat": 15.602,
    "lon": -9.784,
    "type": "بلدية",
    "wilaya": "الحوض الغربي",
    "moughataa": "Kobeni",
    "id": "MR01151",
    "source": "open-admin-data"
  },
  {
    "city": "Tamchekett",
    "name": "Tamchekett",
    "lat": 17.23,
    "lon": -10.66,
    "type": "بلدية",
    "wilaya": "الحوض الغربي",
    "moughataa": "Tamchekett",
    "id": "MR01152",
    "source": "open-admin-data"
  },
  {
    "city": "El Mabrouk 3",
    "name": "El Mabrouk 3",
    "lat": 17.406,
    "lon": -10.39,
    "type": "بلدية",
    "wilaya": "الحوض الغربي",
    "moughataa": "Tamchekett",
    "id": "MR01153",
    "source": "open-admin-data"
  },
  {
    "city": "Radhi",
    "name": "Radhi",
    "lat": 16.722,
    "lon": -10.272,
    "type": "بلدية",
    "wilaya": "الحوض الغربي",
    "moughataa": "Tamchekett",
    "id": "MR01154",
    "source": "open-admin-data"
  },
  {
    "city": "Guetae-Teidoume",
    "name": "Guetae-Teidoume",
    "lat": 16.732,
    "lon": -10.728,
    "type": "بلدية",
    "wilaya": "الحوض الغربي",
    "moughataa": "Tamchekett",
    "id": "MR01155",
    "source": "open-admin-data"
  },
  {
    "city": "Sava",
    "name": "Sava",
    "lat": 17.045,
    "lon": -10.652,
    "type": "بلدية",
    "wilaya": "الحوض الغربي",
    "moughataa": "Tamchekett",
    "id": "MR01156",
    "source": "open-admin-data"
  },
  {
    "city": "Tintan",
    "name": "Tintan",
    "lat": 16.401,
    "lon": -10.183,
    "type": "بلدية",
    "wilaya": "الحوض الغربي",
    "moughataa": "Tintane",
    "id": "MR01157",
    "source": "open-admin-data"
  },
  {
    "city": "Hassi Abdallah",
    "name": "Hassi Abdallah",
    "lat": 16.312,
    "lon": -10.045,
    "type": "بلدية",
    "wilaya": "الحوض الغربي",
    "moughataa": "Tintane",
    "id": "MR01158",
    "source": "open-admin-data"
  },
  {
    "city": "Aweinat Thalle",
    "name": "Aweinat Thalle",
    "lat": 15.938,
    "lon": -10.075,
    "type": "بلدية",
    "wilaya": "الحوض الغربي",
    "moughataa": "Tintane",
    "id": "MR01159",
    "source": "open-admin-data"
  },
  {
    "city": "Aïn Varbe",
    "name": "Aïn Varbe",
    "lat": 15.861,
    "lon": -10.433,
    "type": "بلدية",
    "wilaya": "الحوض الغربي",
    "moughataa": "Tintane",
    "id": "MR01160",
    "source": "open-admin-data"
  },
  {
    "city": "Egharghar",
    "name": "Egharghar",
    "lat": 16.186,
    "lon": -10.46,
    "type": "بلدية",
    "wilaya": "الحوض الغربي",
    "moughataa": "Tintane",
    "id": "MR01161",
    "source": "open-admin-data"
  },
  {
    "city": "Dev-a",
    "name": "Dev-a",
    "lat": 16.417,
    "lon": -10.537,
    "type": "بلدية",
    "wilaya": "الحوض الغربي",
    "moughataa": "Tintane",
    "id": "MR01162",
    "source": "open-admin-data"
  },
  {
    "city": "Touil 2",
    "name": "Touil 2",
    "lat": 15.602,
    "lon": -10.175,
    "type": "بلدية",
    "wilaya": "الحوض الغربي",
    "moughataa": "Touil",
    "id": "MR01163",
    "source": "open-admin-data"
  },
  {
    "city": "Baghdad",
    "name": "Baghdad",
    "lat": 15.598,
    "lon": -10.497,
    "type": "بلدية",
    "wilaya": "الحوض الغربي",
    "moughataa": "Touil",
    "id": "MR01164",
    "source": "open-admin-data"
  },
  {
    "city": "Sett",
    "name": "Sett",
    "lat": 15.579,
    "lon": -10.006,
    "type": "بلدية",
    "wilaya": "الحوض الغربي",
    "moughataa": "Touil",
    "id": "MR01165",
    "source": "open-admin-data"
  },
  {
    "city": "Lehreijat",
    "name": "Lehreijat",
    "lat": 15.598,
    "lon": -10.298,
    "type": "بلدية",
    "wilaya": "الحوض الغربي",
    "moughataa": "Touil",
    "id": "MR01166",
    "source": "open-admin-data"
  },
  {
    "city": "Barkeiwel",
    "name": "Barkeiwel",
    "lat": 16.634,
    "lon": -12.435,
    "type": "بلدية",
    "wilaya": "لعصابه",
    "moughataa": "Barkéol",
    "id": "MR01167",
    "source": "open-admin-data"
  },
  {
    "city": "Gueller",
    "name": "Gueller",
    "lat": 16.864,
    "lon": -12.261,
    "type": "بلدية",
    "wilaya": "لعصابه",
    "moughataa": "Barkéol",
    "id": "MR01168",
    "source": "open-admin-data"
  },
  {
    "city": "Lebheir",
    "name": "Lebheir",
    "lat": 16.521,
    "lon": -12.158,
    "type": "بلدية",
    "wilaya": "لعصابه",
    "moughataa": "Barkéol",
    "id": "MR01169",
    "source": "open-admin-data"
  },
  {
    "city": "Laweissi",
    "name": "Laweissi",
    "lat": 16.235,
    "lon": -12.138,
    "type": "بلدية",
    "wilaya": "لعصابه",
    "moughataa": "Barkéol",
    "id": "MR01170",
    "source": "open-admin-data"
  },
  {
    "city": "Daghveg",
    "name": "Daghveg",
    "lat": 16.464,
    "lon": -12.376,
    "type": "بلدية",
    "wilaya": "لعصابه",
    "moughataa": "Barkéol",
    "id": "MR01171",
    "source": "open-admin-data"
  },
  {
    "city": "El Ghabra",
    "name": "El Ghabra",
    "lat": 16.562,
    "lon": -12.624,
    "type": "بلدية",
    "wilaya": "لعصابه",
    "moughataa": "Barkéol",
    "id": "MR01172",
    "source": "open-admin-data"
  },
  {
    "city": "R'Dheidhie",
    "name": "R'Dheidhie",
    "lat": 16.948,
    "lon": -12.691,
    "type": "بلدية",
    "wilaya": "لعصابه",
    "moughataa": "Barkéol",
    "id": "MR01173",
    "source": "open-admin-data"
  },
  {
    "city": "Bou Lahrath",
    "name": "Bou Lahrath",
    "lat": 17.031,
    "lon": -12.419,
    "type": "بلدية",
    "wilaya": "لعصابه",
    "moughataa": "Barkéol",
    "id": "MR01174",
    "source": "open-admin-data"
  },
  {
    "city": "Boumdeid",
    "name": "Boumdeid",
    "lat": 17.484,
    "lon": -11.367,
    "type": "بلدية",
    "wilaya": "لعصابه",
    "moughataa": "Boumdeid",
    "id": "MR01175",
    "source": "open-admin-data"
  },
  {
    "city": "Hseiy Tin",
    "name": "Hseiy Tin",
    "lat": 17.314,
    "lon": -11.488,
    "type": "بلدية",
    "wilaya": "لعصابه",
    "moughataa": "Boumdeid",
    "id": "MR01176",
    "source": "open-admin-data"
  },
  {
    "city": "Lavtah",
    "name": "Lavtah",
    "lat": 17.853,
    "lon": -11.273,
    "type": "بلدية",
    "wilaya": "لعصابه",
    "moughataa": "Boumdeid",
    "id": "MR01177",
    "source": "open-admin-data"
  },
  {
    "city": "Guerou",
    "name": "Guerou",
    "lat": 16.866,
    "lon": -11.843,
    "type": "بلدية",
    "wilaya": "لعصابه",
    "moughataa": "Guerou",
    "id": "MR01178",
    "source": "open-admin-data"
  },
  {
    "city": "Oudeiy Jrid",
    "name": "Oudeiy Jrid",
    "lat": 16.783,
    "lon": -12.022,
    "type": "بلدية",
    "wilaya": "لعصابه",
    "moughataa": "Guerou",
    "id": "MR01179",
    "source": "open-admin-data"
  },
  {
    "city": "El Ghaira",
    "name": "El Ghaira",
    "lat": 17.157,
    "lon": -12.18,
    "type": "بلدية",
    "wilaya": "لعصابه",
    "moughataa": "Guerou",
    "id": "MR01180",
    "source": "open-admin-data"
  },
  {
    "city": "Kamour",
    "name": "Kamour",
    "lat": 16.995,
    "lon": -11.965,
    "type": "بلدية",
    "wilaya": "لعصابه",
    "moughataa": "Guerou",
    "id": "MR01181",
    "source": "open-admin-data"
  },
  {
    "city": "Kankoussa",
    "name": "Kankoussa",
    "lat": 15.881,
    "lon": -11.532,
    "type": "بلدية",
    "wilaya": "لعصابه",
    "moughataa": "Kankoussa",
    "id": "MR01182",
    "source": "open-admin-data"
  },
  {
    "city": "Sani",
    "name": "Sani",
    "lat": 16.106,
    "lon": -11.46,
    "type": "بلدية",
    "wilaya": "لعصابه",
    "moughataa": "Kankoussa",
    "id": "MR01183",
    "source": "open-admin-data"
  },
  {
    "city": "Blajmil",
    "name": "Blajmil",
    "lat": 16.04,
    "lon": -11.068,
    "type": "بلدية",
    "wilaya": "لعصابه",
    "moughataa": "Kankoussa",
    "id": "MR01184",
    "source": "open-admin-data"
  },
  {
    "city": "Tenaha",
    "name": "Tenaha",
    "lat": 15.47,
    "lon": -10.844,
    "type": "بلدية",
    "wilaya": "لعصابه",
    "moughataa": "Kankoussa",
    "id": "MR01185",
    "source": "open-admin-data"
  },
  {
    "city": "Hamed",
    "name": "Hamed",
    "lat": 15.574,
    "lon": -11.217,
    "type": "بلدية",
    "wilaya": "لعصابه",
    "moughataa": "Kankoussa",
    "id": "MR01186",
    "source": "open-admin-data"
  },
  {
    "city": "Kiffa",
    "name": "Kiffa",
    "lat": 16.626,
    "lon": -11.412,
    "type": "بلدية",
    "wilaya": "لعصابه",
    "moughataa": "Kiffa",
    "id": "MR01187",
    "source": "open-admin-data"
  },
  {
    "city": "Nouamlein",
    "name": "Nouamlein",
    "lat": 17.11,
    "lon": -11.469,
    "type": "بلدية",
    "wilaya": "لعصابه",
    "moughataa": "Kiffa",
    "id": "MR01188",
    "source": "open-admin-data"
  },
  {
    "city": "Aghorat",
    "name": "Aghorat",
    "lat": 16.724,
    "lon": -10.95,
    "type": "بلدية",
    "wilaya": "لعصابه",
    "moughataa": "Kiffa",
    "id": "MR01189",
    "source": "open-admin-data"
  },
  {
    "city": "El Melgue",
    "name": "El Melgue",
    "lat": 16.701,
    "lon": -11.111,
    "type": "بلدية",
    "wilaya": "لعصابه",
    "moughataa": "Kiffa",
    "id": "MR01190",
    "source": "open-admin-data"
  },
  {
    "city": "Kouroudjel",
    "name": "Kouroudjel",
    "lat": 16.423,
    "lon": -11.495,
    "type": "بلدية",
    "wilaya": "لعصابه",
    "moughataa": "Kiffa",
    "id": "MR01191",
    "source": "open-admin-data"
  },
  {
    "city": "Legrane",
    "name": "Legrane",
    "lat": 16.36,
    "lon": -11.797,
    "type": "بلدية",
    "wilaya": "لعصابه",
    "moughataa": "Kiffa",
    "id": "MR01192",
    "source": "open-admin-data"
  },
  {
    "city": "Kaedi",
    "name": "Kaedi",
    "lat": 16.179,
    "lon": -13.477,
    "type": "بلدية",
    "wilaya": "كوركول",
    "moughataa": "Kaedi",
    "id": "MR01193",
    "source": "open-admin-data"
  },
  {
    "city": "Néré Walo",
    "name": "Néré Walo",
    "lat": 16.228,
    "lon": -13.579,
    "type": "بلدية",
    "wilaya": "كوركول",
    "moughataa": "Kaedi",
    "id": "MR01194",
    "source": "open-admin-data"
  },
  {
    "city": "Djewol",
    "name": "Djewol",
    "lat": 16.084,
    "lon": -13.347,
    "type": "بلدية",
    "wilaya": "كوركول",
    "moughataa": "Kaedi",
    "id": "MR01195",
    "source": "open-admin-data"
  },
  {
    "city": "Toghomadi",
    "name": "Toghomadi",
    "lat": 15.856,
    "lon": -13.163,
    "type": "بلدية",
    "wilaya": "كوركول",
    "moughataa": "Kaedi",
    "id": "MR01196",
    "source": "open-admin-data"
  },
  {
    "city": "Tifondé Civé",
    "name": "Tifondé Civé",
    "lat": 15.822,
    "lon": -12.988,
    "type": "بلدية",
    "wilaya": "كوركول",
    "moughataa": "Kaedi",
    "id": "MR01197",
    "source": "open-admin-data"
  },
  {
    "city": "Maghama",
    "name": "Maghama",
    "lat": 15.511,
    "lon": -12.846,
    "type": "بلدية",
    "wilaya": "كوركول",
    "moughataa": "Maghama",
    "id": "MR01198",
    "source": "open-admin-data"
  },
  {
    "city": "Doo",
    "name": "Doo",
    "lat": 15.507,
    "lon": -12.996,
    "type": "بلدية",
    "wilaya": "كوركول",
    "moughataa": "Maghama",
    "id": "MR01199",
    "source": "open-admin-data"
  },
  {
    "city": "Dolol Civé",
    "name": "Dolol Civé",
    "lat": 15.584,
    "lon": -13.044,
    "type": "بلدية",
    "wilaya": "كوركول",
    "moughataa": "Maghama",
    "id": "MR01200",
    "source": "open-admin-data"
  },
  {
    "city": "Beilouguet Litame",
    "name": "Beilouguet Litame",
    "lat": 15.756,
    "lon": -12.871,
    "type": "بلدية",
    "wilaya": "كوركول",
    "moughataa": "Maghama",
    "id": "MR01201",
    "source": "open-admin-data"
  },
  {
    "city": "Vrea Litame",
    "name": "Vrea Litame",
    "lat": 15.5,
    "lon": -12.7,
    "type": "بلدية",
    "wilaya": "كوركول",
    "moughataa": "Maghama",
    "id": "MR01202",
    "source": "open-admin-data"
  },
  {
    "city": "Toulel",
    "name": "Toulel",
    "lat": 15.366,
    "lon": -12.768,
    "type": "بلدية",
    "wilaya": "كوركول",
    "moughataa": "Maghama",
    "id": "MR01203",
    "source": "open-admin-data"
  },
  {
    "city": "Sagné",
    "name": "Sagné",
    "lat": 15.212,
    "lon": -12.762,
    "type": "بلدية",
    "wilaya": "كوركول",
    "moughataa": "Maghama",
    "id": "MR01204",
    "source": "open-admin-data"
  },
  {
    "city": "Wali Djantang",
    "name": "Wali Djantang",
    "lat": 15.37,
    "lon": -12.906,
    "type": "بلدية",
    "wilaya": "كوركول",
    "moughataa": "Maghama",
    "id": "MR01205",
    "source": "open-admin-data"
  },
  {
    "city": "M'Boud",
    "name": "M'Boud",
    "lat": 16.025,
    "lon": -12.575,
    "type": "بلدية",
    "wilaya": "كوركول",
    "moughataa": "M'Bout",
    "id": "MR01206",
    "source": "open-admin-data"
  },
  {
    "city": "Tikobra",
    "name": "Tikobra",
    "lat": 16.143,
    "lon": -12.376,
    "type": "بلدية",
    "wilaya": "كوركول",
    "moughataa": "M'Bout",
    "id": "MR01207",
    "source": "open-admin-data"
  },
  {
    "city": "Terenguel Ehel Moulaye Ely",
    "name": "Terenguel Ehel Moulaye Ely",
    "lat": 15.867,
    "lon": -12.381,
    "type": "بلدية",
    "wilaya": "كوركول",
    "moughataa": "M'Bout",
    "id": "MR01208",
    "source": "open-admin-data"
  },
  {
    "city": "N'Djadjbenni Gandéga",
    "name": "N'Djadjbenni Gandéga",
    "lat": 15.803,
    "lon": -12.523,
    "type": "بلدية",
    "wilaya": "كوركول",
    "moughataa": "M'Bout",
    "id": "MR01209",
    "source": "open-admin-data"
  },
  {
    "city": "Edebaye Ehel Guelaye",
    "name": "Edebaye Ehel Guelaye",
    "lat": 15.763,
    "lon": -12.681,
    "type": "بلدية",
    "wilaya": "كوركول",
    "moughataa": "M'Bout",
    "id": "MR01210",
    "source": "open-admin-data"
  },
  {
    "city": "Voum Legleite",
    "name": "Voum Legleite",
    "lat": 16.043,
    "lon": -12.705,
    "type": "بلدية",
    "wilaya": "كوركول",
    "moughataa": "M'Bout",
    "id": "MR01211",
    "source": "open-admin-data"
  },
  {
    "city": "Chelkhet Tiyab",
    "name": "Chelkhet Tiyab",
    "lat": 16.329,
    "lon": -12.77,
    "type": "بلدية",
    "wilaya": "كوركول",
    "moughataa": "M'Bout",
    "id": "MR01212",
    "source": "open-admin-data"
  },
  {
    "city": "Lahrach",
    "name": "Lahrach",
    "lat": 16.286,
    "lon": -12.54,
    "type": "بلدية",
    "wilaya": "كوركول",
    "moughataa": "M'Bout",
    "id": "MR01213",
    "source": "open-admin-data"
  },
  {
    "city": "Souve",
    "name": "Souve",
    "lat": 15.993,
    "lon": -12.148,
    "type": "بلدية",
    "wilaya": "كوركول",
    "moughataa": "M'Bout",
    "id": "MR01214",
    "source": "open-admin-data"
  },
  {
    "city": "Mounguel",
    "name": "Mounguel",
    "lat": 16.383,
    "lon": -13.135,
    "type": "بلدية",
    "wilaya": "كوركول",
    "moughataa": "Mounguel",
    "id": "MR01215",
    "source": "open-admin-data"
  },
  {
    "city": "Bathet Moït",
    "name": "Bathet Moït",
    "lat": 16.483,
    "lon": -13.084,
    "type": "بلدية",
    "wilaya": "كوركول",
    "moughataa": "Mounguel",
    "id": "MR01216",
    "source": "open-admin-data"
  },
  {
    "city": "Bokhol",
    "name": "Bokhol",
    "lat": 16.49,
    "lon": -12.943,
    "type": "بلدية",
    "wilaya": "كوركول",
    "moughataa": "Mounguel",
    "id": "MR01217",
    "source": "open-admin-data"
  },
  {
    "city": "Melzem Teichet",
    "name": "Melzem Teichet",
    "lat": 16.607,
    "lon": -12.865,
    "type": "بلدية",
    "wilaya": "كوركول",
    "moughataa": "Mounguel",
    "id": "MR01218",
    "source": "open-admin-data"
  },
  {
    "city": "Azgueilem Tiyab",
    "name": "Azgueilem Tiyab",
    "lat": 16.342,
    "lon": -13.031,
    "type": "بلدية",
    "wilaya": "كوركول",
    "moughataa": "Mounguel",
    "id": "MR01219",
    "source": "open-admin-data"
  },
  {
    "city": "Lexeiba 1",
    "name": "Lexeiba 1",
    "lat": 16.209,
    "lon": -13.1,
    "type": "بلدية",
    "wilaya": "كوركول",
    "moughataa": "Lexeibe 1",
    "id": "MR01220",
    "source": "open-admin-data"
  },
  {
    "city": "Betengal",
    "name": "Betengal",
    "lat": 16.109,
    "lon": -12.945,
    "type": "بلدية",
    "wilaya": "كوركول",
    "moughataa": "Lexeibe 1",
    "id": "MR01221",
    "source": "open-admin-data"
  },
  {
    "city": "Talhaye",
    "name": "Talhaye",
    "lat": 16.062,
    "lon": -13.148,
    "type": "بلدية",
    "wilaya": "كوركول",
    "moughataa": "Lexeibe 1",
    "id": "MR01222",
    "source": "open-admin-data"
  },
  {
    "city": "Ganki",
    "name": "Ganki",
    "lat": 16.306,
    "lon": -13.384,
    "type": "بلدية",
    "wilaya": "كوركول",
    "moughataa": "Lexeibe 1",
    "id": "MR01223",
    "source": "open-admin-data"
  },
  {
    "city": "Aleg",
    "name": "Aleg",
    "lat": 17.043,
    "lon": -13.94,
    "type": "بلدية",
    "wilaya": "البراكنة",
    "moughataa": "Aleg",
    "id": "MR01224",
    "source": "open-admin-data"
  },
  {
    "city": "Chegar",
    "name": "Chegar",
    "lat": 17.415,
    "lon": -13.542,
    "type": "بلدية",
    "wilaya": "البراكنة",
    "moughataa": "Aleg",
    "id": "MR01225",
    "source": "open-admin-data"
  },
  {
    "city": "Bouhdida",
    "name": "Bouhdida",
    "lat": 16.908,
    "lon": -14.171,
    "type": "بلدية",
    "wilaya": "البراكنة",
    "moughataa": "Aleg",
    "id": "MR01226",
    "source": "open-admin-data"
  },
  {
    "city": "Aghchourguit",
    "name": "Aghchourguit",
    "lat": 17.457,
    "lon": -13.894,
    "type": "بلدية",
    "wilaya": "البراكنة",
    "moughataa": "Aleg",
    "id": "MR01227",
    "source": "open-admin-data"
  },
  {
    "city": "Bababé",
    "name": "Bababé",
    "lat": 16.332,
    "lon": -13.945,
    "type": "بلدية",
    "wilaya": "البراكنة",
    "moughataa": "Bababé",
    "id": "MR01228",
    "source": "open-admin-data"
  },
  {
    "city": "El Verae",
    "name": "El Verae",
    "lat": 16.434,
    "lon": -13.866,
    "type": "بلدية",
    "wilaya": "البراكنة",
    "moughataa": "Bababé",
    "id": "MR01229",
    "source": "open-admin-data"
  },
  {
    "city": "Aéré M'Bar",
    "name": "Aéré M'Bar",
    "lat": 16.476,
    "lon": -14.031,
    "type": "بلدية",
    "wilaya": "البراكنة",
    "moughataa": "Bababé",
    "id": "MR01230",
    "source": "open-admin-data"
  },
  {
    "city": "Boghé",
    "name": "Boghé",
    "lat": 16.6,
    "lon": -14.216,
    "type": "بلدية",
    "wilaya": "البراكنة",
    "moughataa": "Boghé",
    "id": "MR01231",
    "source": "open-admin-data"
  },
  {
    "city": "Dar El Aviye",
    "name": "Dar El Aviye",
    "lat": 16.681,
    "lon": -14.363,
    "type": "بلدية",
    "wilaya": "البراكنة",
    "moughataa": "Boghé",
    "id": "MR01232",
    "source": "open-admin-data"
  },
  {
    "city": "Dar El Barke",
    "name": "Dar El Barke",
    "lat": 16.695,
    "lon": -14.777,
    "type": "بلدية",
    "wilaya": "البراكنة",
    "moughataa": "Boghé",
    "id": "MR01233",
    "source": "open-admin-data"
  },
  {
    "city": "Ould Biram",
    "name": "Ould Biram",
    "lat": 16.696,
    "lon": -14.527,
    "type": "بلدية",
    "wilaya": "البراكنة",
    "moughataa": "Boghé",
    "id": "MR01234",
    "source": "open-admin-data"
  },
  {
    "city": "Magtalahjar",
    "name": "Magtalahjar",
    "lat": 17.918,
    "lon": -13.039,
    "type": "بلدية",
    "wilaya": "البراكنة",
    "moughataa": "Magtalahjar",
    "id": "MR01235",
    "source": "open-admin-data"
  },
  {
    "city": "Sangrave",
    "name": "Sangrave",
    "lat": 17.516,
    "lon": -12.75,
    "type": "بلدية",
    "wilaya": "البراكنة",
    "moughataa": "Magtalahjar",
    "id": "MR01236",
    "source": "open-admin-data"
  },
  {
    "city": "Djonabe",
    "name": "Djonabe",
    "lat": 17.137,
    "lon": -12.691,
    "type": "بلدية",
    "wilaya": "البراكنة",
    "moughataa": "Magtalahjar",
    "id": "MR01237",
    "source": "open-admin-data"
  },
  {
    "city": "Ouad Emmour",
    "name": "Ouad Emmour",
    "lat": 17.282,
    "lon": -12.972,
    "type": "بلدية",
    "wilaya": "البراكنة",
    "moughataa": "Magtalahjar",
    "id": "MR01238",
    "source": "open-admin-data"
  },
  {
    "city": "M'Bagne",
    "name": "M'Bagne",
    "lat": 16.157,
    "lon": -13.781,
    "type": "بلدية",
    "wilaya": "البراكنة",
    "moughataa": "M'Bagne",
    "id": "MR01239",
    "source": "open-admin-data"
  },
  {
    "city": "Niabina",
    "name": "Niabina",
    "lat": 16.232,
    "lon": -13.848,
    "type": "بلدية",
    "wilaya": "البراكنة",
    "moughataa": "M'Bagne",
    "id": "MR01240",
    "source": "open-admin-data"
  },
  {
    "city": "Edebaye El Hejjaj",
    "name": "Edebaye El Hejjaj",
    "lat": 16.36,
    "lon": -13.767,
    "type": "بلدية",
    "wilaya": "البراكنة",
    "moughataa": "M'Bagne",
    "id": "MR01241",
    "source": "open-admin-data"
  },
  {
    "city": "Bagodine",
    "name": "Bagodine",
    "lat": 16.227,
    "lon": -13.7,
    "type": "بلدية",
    "wilaya": "البراكنة",
    "moughataa": "M'Bagne",
    "id": "MR01242",
    "source": "open-admin-data"
  },
  {
    "city": "Maal",
    "name": "Maal",
    "lat": 17.066,
    "lon": -13.459,
    "type": "بلدية",
    "wilaya": "البراكنة",
    "moughataa": "Maal",
    "id": "MR01243",
    "source": "open-admin-data"
  },
  {
    "city": "Roumed",
    "name": "Roumed",
    "lat": 16.968,
    "lon": -13.174,
    "type": "بلدية",
    "wilaya": "البراكنة",
    "moughataa": "Maal",
    "id": "MR01244",
    "source": "open-admin-data"
  },
  {
    "city": "Elwad Lebiadh",
    "name": "Elwad Lebiadh",
    "lat": 16.87,
    "lon": -12.966,
    "type": "بلدية",
    "wilaya": "البراكنة",
    "moughataa": "Maal",
    "id": "MR01245",
    "source": "open-admin-data"
  },
  {
    "city": "Bourat",
    "name": "Bourat",
    "lat": 16.652,
    "lon": -13.114,
    "type": "بلدية",
    "wilaya": "البراكنة",
    "moughataa": "Maal",
    "id": "MR01246",
    "source": "open-admin-data"
  },
  {
    "city": "Djelwar",
    "name": "Djelwar",
    "lat": 16.597,
    "lon": -13.503,
    "type": "بلدية",
    "wilaya": "البراكنة",
    "moughataa": "Maal",
    "id": "MR01247",
    "source": "open-admin-data"
  },
  {
    "city": "Boutilimit",
    "name": "Boutilimit",
    "lat": 17.54,
    "lon": -14.693,
    "type": "بلدية",
    "wilaya": "الترارزة",
    "moughataa": "Boutilimit",
    "id": "MR01248",
    "source": "open-admin-data"
  },
  {
    "city": "Elb Adress",
    "name": "Elb Adress",
    "lat": 18.279,
    "lon": -13.42,
    "type": "بلدية",
    "wilaya": "الترارزة",
    "moughataa": "Boutilimit",
    "id": "MR01249",
    "source": "open-admin-data"
  },
  {
    "city": "Ajoueir",
    "name": "Ajoueir",
    "lat": 17.206,
    "lon": -14.423,
    "type": "بلدية",
    "wilaya": "الترارزة",
    "moughataa": "Boutilimit",
    "id": "MR01250",
    "source": "open-admin-data"
  },
  {
    "city": "N'Teichet",
    "name": "N'Teichet",
    "lat": 17.334,
    "lon": -14.701,
    "type": "بلدية",
    "wilaya": "الترارزة",
    "moughataa": "Boutilimit",
    "id": "MR01251",
    "source": "open-admin-data"
  },
  {
    "city": "Nebaghiye",
    "name": "Nebaghiye",
    "lat": 17.406,
    "lon": -15.06,
    "type": "بلدية",
    "wilaya": "الترارزة",
    "moughataa": "Boutilimit",
    "id": "MR01252",
    "source": "open-admin-data"
  },
  {
    "city": "Tenghadej",
    "name": "Tenghadej",
    "lat": 18.548,
    "lon": -14.389,
    "type": "بلدية",
    "wilaya": "الترارزة",
    "moughataa": "Boutilimit",
    "id": "MR01253",
    "source": "open-admin-data"
  },
  {
    "city": "El Mouyessar",
    "name": "El Mouyessar",
    "lat": 18.499,
    "lon": -13.887,
    "type": "بلدية",
    "wilaya": "الترارزة",
    "moughataa": "Boutilimit",
    "id": "MR01254",
    "source": "open-admin-data"
  },
  {
    "city": "Keurmacen",
    "name": "Keurmacen",
    "lat": 16.568,
    "lon": -16.203,
    "type": "بلدية",
    "wilaya": "الترارزة",
    "moughataa": "Keur Macen",
    "id": "MR01255",
    "source": "open-admin-data"
  },
  {
    "city": "N'Diago",
    "name": "N'Diago",
    "lat": 16.333,
    "lon": -16.431,
    "type": "بلدية",
    "wilaya": "الترارزة",
    "moughataa": "Keur Macen",
    "id": "MR01256",
    "source": "open-admin-data"
  },
  {
    "city": "M'Balal",
    "name": "M'Balal",
    "lat": 16.75,
    "lon": -16.237,
    "type": "بلدية",
    "wilaya": "الترارزة",
    "moughataa": "Keur Macen",
    "id": "MR01257",
    "source": "open-admin-data"
  },
  {
    "city": "Mederdra",
    "name": "Mederdra",
    "lat": 16.936,
    "lon": -15.68,
    "type": "بلدية",
    "wilaya": "الترارزة",
    "moughataa": "Mederdra",
    "id": "MR01258",
    "source": "open-admin-data"
  },
  {
    "city": "Beir Taouress",
    "name": "Beir Taouress",
    "lat": 17.092,
    "lon": -15.698,
    "type": "بلدية",
    "wilaya": "الترارزة",
    "moughataa": "Mederdra",
    "id": "MR01259",
    "source": "open-admin-data"
  },
  {
    "city": "Taguilalet",
    "name": "Taguilalet",
    "lat": 17.23,
    "lon": -15.405,
    "type": "بلدية",
    "wilaya": "الترارزة",
    "moughataa": "Mederdra",
    "id": "MR01260",
    "source": "open-admin-data"
  },
  {
    "city": "El Khat",
    "name": "El Khat",
    "lat": 16.809,
    "lon": -15.83,
    "type": "بلدية",
    "wilaya": "الترارزة",
    "moughataa": "Mederdra",
    "id": "MR01261",
    "source": "open-admin-data"
  },
  {
    "city": "Tiguent (El Jedide)",
    "name": "Tiguent (El Jedide)",
    "lat": 17.268,
    "lon": -15.952,
    "type": "بلدية",
    "wilaya": "الترارزة",
    "moughataa": "Mederdra",
    "id": "MR01262",
    "source": "open-admin-data"
  },
  {
    "city": "Ouad Naga",
    "name": "Ouad Naga",
    "lat": 17.947,
    "lon": -15.512,
    "type": "بلدية",
    "wilaya": "الترارزة",
    "moughataa": "Ouad Naga",
    "id": "MR01263",
    "source": "open-admin-data"
  },
  {
    "city": "Aouleiygat",
    "name": "Aouleiygat",
    "lat": 18.203,
    "lon": -15.408,
    "type": "بلدية",
    "wilaya": "الترارزة",
    "moughataa": "Ouad Naga",
    "id": "MR01264",
    "source": "open-admin-data"
  },
  {
    "city": "El Ariye",
    "name": "El Ariye",
    "lat": 17.664,
    "lon": -15.883,
    "type": "بلدية",
    "wilaya": "الترارزة",
    "moughataa": "Ouad Naga",
    "id": "MR01265",
    "source": "open-admin-data"
  },
  {
    "city": "R'Kiz",
    "name": "R'Kiz",
    "lat": 16.917,
    "lon": -15.209,
    "type": "بلدية",
    "wilaya": "الترارزة",
    "moughataa": "R'Kiz",
    "id": "MR01266",
    "source": "open-admin-data"
  },
  {
    "city": "Boutalhaye",
    "name": "Boutalhaye",
    "lat": 17.053,
    "lon": -14.926,
    "type": "بلدية",
    "wilaya": "الترارزة",
    "moughataa": "R'Kiz",
    "id": "MR01267",
    "source": "open-admin-data"
  },
  {
    "city": "Bareine",
    "name": "Bareine",
    "lat": 17.154,
    "lon": -15.189,
    "type": "بلدية",
    "wilaya": "الترارزة",
    "moughataa": "R'Kiz",
    "id": "MR01268",
    "source": "open-admin-data"
  },
  {
    "city": "Rosso",
    "name": "Rosso",
    "lat": 16.582,
    "lon": -15.814,
    "type": "بلدية",
    "wilaya": "الترارزة",
    "moughataa": "Rosso",
    "id": "MR01269",
    "source": "open-admin-data"
  },
  {
    "city": "Jedrel Mouhguen",
    "name": "Jedrel Mouhguen",
    "lat": 16.676,
    "lon": -15.604,
    "type": "بلدية",
    "wilaya": "الترارزة",
    "moughataa": "Rosso",
    "id": "MR01270",
    "source": "open-admin-data"
  },
  {
    "city": "Teikane",
    "name": "Teikane",
    "lat": 16.599,
    "lon": -15.275,
    "type": "بلدية",
    "wilaya": "الترارزة",
    "moughataa": "Tekane",
    "id": "MR01271",
    "source": "open-admin-data"
  },
  {
    "city": "Chemame",
    "name": "Chemame",
    "lat": 16.765,
    "lon": -15.266,
    "type": "بلدية",
    "wilaya": "الترارزة",
    "moughataa": "Tekane",
    "id": "MR01272",
    "source": "open-admin-data"
  },
  {
    "city": "Teichteyat",
    "name": "Teichteyat",
    "lat": 16.805,
    "lon": -15.403,
    "type": "بلدية",
    "wilaya": "الترارزة",
    "moughataa": "Tekane",
    "id": "MR01273",
    "source": "open-admin-data"
  },
  {
    "city": "Lexelbe 2",
    "name": "Lexelbe 2",
    "lat": 16.782,
    "lon": -14.989,
    "type": "بلدية",
    "wilaya": "الترارزة",
    "moughataa": "Tekane",
    "id": "MR01274",
    "source": "open-admin-data"
  },
  {
    "city": "Aoujeft",
    "name": "Aoujeft",
    "lat": 20.009,
    "lon": -13.049,
    "type": "بلدية",
    "wilaya": "آدرار",
    "moughataa": "Aoujeft",
    "id": "MR01275",
    "source": "open-admin-data"
  },
  {
    "city": "Maeden",
    "name": "Maeden",
    "lat": 20.195,
    "lon": -13.028,
    "type": "بلدية",
    "wilaya": "آدرار",
    "moughataa": "Aoujeft",
    "id": "MR01276",
    "source": "open-admin-data"
  },
  {
    "city": "N'Teirguent",
    "name": "N'Teirguent",
    "lat": 19.095,
    "lon": -12.676,
    "type": "بلدية",
    "wilaya": "آدرار",
    "moughataa": "Aoujeft",
    "id": "MR01277",
    "source": "open-admin-data"
  },
  {
    "city": "El Medah",
    "name": "El Medah",
    "lat": 19.5,
    "lon": -13.735,
    "type": "بلدية",
    "wilaya": "آدرار",
    "moughataa": "Aoujeft",
    "id": "MR01278",
    "source": "open-admin-data"
  },
  {
    "city": "Atar",
    "name": "Atar",
    "lat": 20.503,
    "lon": -13.042,
    "type": "بلدية",
    "wilaya": "آدرار",
    "moughataa": "Atar",
    "id": "MR01279",
    "source": "open-admin-data"
  },
  {
    "city": "Aïn Ehel Taya",
    "name": "Aïn Ehel Taya",
    "lat": 20.208,
    "lon": -13.646,
    "type": "بلدية",
    "wilaya": "آدرار",
    "moughataa": "Atar",
    "id": "MR01280",
    "source": "open-admin-data"
  },
  {
    "city": "Tawaz",
    "name": "Tawaz",
    "lat": 20.797,
    "lon": -13.297,
    "type": "بلدية",
    "wilaya": "آدرار",
    "moughataa": "Atar",
    "id": "MR01281",
    "source": "open-admin-data"
  },
  {
    "city": "Choum",
    "name": "Choum",
    "lat": 21.365,
    "lon": -12.708,
    "type": "بلدية",
    "wilaya": "آدرار",
    "moughataa": "Atar",
    "id": "MR01282",
    "source": "open-admin-data"
  },
  {
    "city": "Chinguitti",
    "name": "Chinguitti",
    "lat": 20.177,
    "lon": -10.245,
    "type": "بلدية",
    "wilaya": "آدرار",
    "moughataa": "Chinguitti",
    "id": "MR01283",
    "source": "open-admin-data"
  },
  {
    "city": "Aïn Savra",
    "name": "Aïn Savra",
    "lat": 19.612,
    "lon": -11.968,
    "type": "بلدية",
    "wilaya": "آدرار",
    "moughataa": "Chinguitti",
    "id": "MR01284",
    "source": "open-admin-data"
  },
  {
    "city": "Ouadane",
    "name": "Ouadane",
    "lat": 22.348,
    "lon": -8.142,
    "type": "بلدية",
    "wilaya": "آدرار",
    "moughataa": "Ouadane",
    "id": "MR01285",
    "source": "open-admin-data"
  },
  {
    "city": "Nouadhibou",
    "name": "Nouadhibou",
    "lat": 20.902,
    "lon": -17.064,
    "type": "بلدية",
    "wilaya": "داخلة نواذيبو",
    "moughataa": "Nouadhibou",
    "id": "MR01286",
    "source": "open-admin-data"
  },
  {
    "city": "Boulenouar",
    "name": "Boulenouar",
    "lat": 20.928,
    "lon": -16.168,
    "type": "بلدية",
    "wilaya": "داخلة نواذيبو",
    "moughataa": "Nouadhibou",
    "id": "MR01287",
    "source": "open-admin-data"
  },
  {
    "city": "Inal",
    "name": "Inal",
    "lat": 20.946,
    "lon": -15.313,
    "type": "بلدية",
    "wilaya": "داخلة نواذيبو",
    "moughataa": "Nouadhibou",
    "id": "MR01288",
    "source": "open-admin-data"
  },
  {
    "city": "Chami",
    "name": "Chami",
    "lat": 20.352,
    "lon": -15.92,
    "type": "بلدية",
    "wilaya": "داخلة نواذيبو",
    "moughataa": "Chami",
    "id": "MR01289",
    "source": "open-admin-data"
  },
  {
    "city": "Tmeimichat",
    "name": "Tmeimichat",
    "lat": 20.833,
    "lon": -14.779,
    "type": "بلدية",
    "wilaya": "داخلة نواذيبو",
    "moughataa": "Chami",
    "id": "MR01290",
    "source": "open-admin-data"
  },
  {
    "city": "Nouamghar",
    "name": "Nouamghar",
    "lat": 19.504,
    "lon": -15.992,
    "type": "بلدية",
    "wilaya": "داخلة نواذيبو",
    "moughataa": "Chami",
    "id": "MR01291",
    "source": "open-admin-data"
  },
  {
    "city": "Moudjeria",
    "name": "Moudjeria",
    "lat": 17.915,
    "lon": -12.334,
    "type": "بلدية",
    "wilaya": "تكانت",
    "moughataa": "Moudjeria",
    "id": "MR01292",
    "source": "open-admin-data"
  },
  {
    "city": "N'Beike",
    "name": "N'Beike",
    "lat": 18.166,
    "lon": -12.241,
    "type": "بلدية",
    "wilaya": "تكانت",
    "moughataa": "Moudjeria",
    "id": "MR01293",
    "source": "open-admin-data"
  },
  {
    "city": "Soudoud",
    "name": "Soudoud",
    "lat": 17.538,
    "lon": -12.127,
    "type": "بلدية",
    "wilaya": "تكانت",
    "moughataa": "Moudjeria",
    "id": "MR01294",
    "source": "open-admin-data"
  },
  {
    "city": "Tichit",
    "name": "Tichit",
    "lat": 18.498,
    "lon": -9.314,
    "type": "بلدية",
    "wilaya": "تكانت",
    "moughataa": "Tichit",
    "id": "MR01295",
    "source": "open-admin-data"
  },
  {
    "city": "Lekhcheb",
    "name": "Lekhcheb",
    "lat": 18.537,
    "lon": -10.551,
    "type": "بلدية",
    "wilaya": "تكانت",
    "moughataa": "Tichit",
    "id": "MR01296",
    "source": "open-admin-data"
  },
  {
    "city": "Tidjikdja",
    "name": "Tidjikdja",
    "lat": 18.399,
    "lon": -11.236,
    "type": "بلدية",
    "wilaya": "تكانت",
    "moughataa": "Tidjikja",
    "id": "MR01297",
    "source": "open-admin-data"
  },
  {
    "city": "El Wahat",
    "name": "El Wahat",
    "lat": 19.043,
    "lon": -11.547,
    "type": "بلدية",
    "wilaya": "تكانت",
    "moughataa": "Tidjikja",
    "id": "MR01298",
    "source": "open-admin-data"
  },
  {
    "city": "Tensigh",
    "name": "Tensigh",
    "lat": 18.21,
    "lon": -11.758,
    "type": "بلدية",
    "wilaya": "تكانت",
    "moughataa": "Tidjikja",
    "id": "MR01299",
    "source": "open-admin-data"
  },
  {
    "city": "Boubacar Ben Amer",
    "name": "Boubacar Ben Amer",
    "lat": 17.839,
    "lon": -11.641,
    "type": "بلدية",
    "wilaya": "تكانت",
    "moughataa": "Tidjikja",
    "id": "MR01300",
    "source": "open-admin-data"
  },
  {
    "city": "Lehsira",
    "name": "Lehsira",
    "lat": 17.495,
    "lon": -11.604,
    "type": "بلدية",
    "wilaya": "تكانت",
    "moughataa": "Tidjikja",
    "id": "MR01301",
    "source": "open-admin-data"
  },
  {
    "city": "Ould Yengé",
    "name": "Ould Yengé",
    "lat": 15.543,
    "lon": -11.738,
    "type": "بلدية",
    "wilaya": "كيدماغا",
    "moughataa": "Ould Yengé",
    "id": "MR01302",
    "source": "open-admin-data"
  },
  {
    "city": "Leebelli",
    "name": "Leebelli",
    "lat": 15.354,
    "lon": -11.863,
    "type": "بلدية",
    "wilaya": "كيدماغا",
    "moughataa": "Ould Yengé",
    "id": "MR01303",
    "source": "open-admin-data"
  },
  {
    "city": "Tektake",
    "name": "Tektake",
    "lat": 15.619,
    "lon": -11.93,
    "type": "بلدية",
    "wilaya": "كيدماغا",
    "moughataa": "Ould Yengé",
    "id": "MR01304",
    "source": "open-admin-data"
  },
  {
    "city": "Davoue",
    "name": "Davoue",
    "lat": 15.588,
    "lon": -12.064,
    "type": "بلدية",
    "wilaya": "كيدماغا",
    "moughataa": "Ould Yengé",
    "id": "MR01305",
    "source": "open-admin-data"
  },
  {
    "city": "Bouanz",
    "name": "Bouanz",
    "lat": 15.828,
    "lon": -12.121,
    "type": "بلدية",
    "wilaya": "كيدماغا",
    "moughataa": "Ould Yengé",
    "id": "MR01306",
    "source": "open-admin-data"
  },
  {
    "city": "Lehraj",
    "name": "Lehraj",
    "lat": 15.88,
    "lon": -11.801,
    "type": "بلدية",
    "wilaya": "كيدماغا",
    "moughataa": "Ould Yengé",
    "id": "MR01307",
    "source": "open-admin-data"
  },
  {
    "city": "Leaweinat",
    "name": "Leaweinat",
    "lat": 15.692,
    "lon": -11.761,
    "type": "بلدية",
    "wilaya": "كيدماغا",
    "moughataa": "Ould Yengé",
    "id": "MR01308",
    "source": "open-admin-data"
  },
  {
    "city": "Sélibabi",
    "name": "Sélibabi",
    "lat": 15.159,
    "lon": -12.183,
    "type": "بلدية",
    "wilaya": "كيدماغا",
    "moughataa": "Sélibaby",
    "id": "MR01309",
    "source": "open-admin-data"
  },
  {
    "city": "Ould M'Bonny",
    "name": "Ould M'Bonny",
    "lat": 15.723,
    "lon": -12.275,
    "type": "بلدية",
    "wilaya": "كيدماغا",
    "moughataa": "Sélibaby",
    "id": "MR01310",
    "source": "open-admin-data"
  },
  {
    "city": "Tachout",
    "name": "Tachout",
    "lat": 15.448,
    "lon": -12.181,
    "type": "بلدية",
    "wilaya": "كيدماغا",
    "moughataa": "Sélibaby",
    "id": "MR01311",
    "source": "open-admin-data"
  },
  {
    "city": "Hassi Chegar",
    "name": "Hassi Chegar",
    "lat": 15.337,
    "lon": -12.1,
    "type": "بلدية",
    "wilaya": "كيدماغا",
    "moughataa": "Sélibaby",
    "id": "MR01312",
    "source": "open-admin-data"
  },
  {
    "city": "Ghabou",
    "name": "Ghabou",
    "lat": 14.805,
    "lon": -12.057,
    "type": "بلدية",
    "wilaya": "كيدماغا",
    "moughataa": "Ghabou",
    "id": "MR01313",
    "source": "open-admin-data"
  },
  {
    "city": "Chleikha",
    "name": "Chleikha",
    "lat": 14.872,
    "lon": -11.981,
    "type": "بلدية",
    "wilaya": "كيدماغا",
    "moughataa": "Ghabou",
    "id": "MR01314",
    "source": "open-admin-data"
  },
  {
    "city": "Diogountou",
    "name": "Diogountou",
    "lat": 14.958,
    "lon": -12.201,
    "type": "بلدية",
    "wilaya": "كيدماغا",
    "moughataa": "Ghabou",
    "id": "MR01315",
    "source": "open-admin-data"
  },
  {
    "city": "Bayediam",
    "name": "Bayediam",
    "lat": 15.046,
    "lon": -11.984,
    "type": "بلدية",
    "wilaya": "كيدماغا",
    "moughataa": "Ghabou",
    "id": "MR01316",
    "source": "open-admin-data"
  },
  {
    "city": "Gouraye",
    "name": "Gouraye",
    "lat": 15.002,
    "lon": -12.376,
    "type": "بلدية",
    "wilaya": "كيدماغا",
    "moughataa": "Ghabou",
    "id": "MR01317",
    "source": "open-admin-data"
  },
  {
    "city": "Soufi",
    "name": "Soufi",
    "lat": 15.232,
    "lon": -11.984,
    "type": "بلدية",
    "wilaya": "كيدماغا",
    "moughataa": "Ghabou",
    "id": "MR01318",
    "source": "open-admin-data"
  },
  {
    "city": "Wompou",
    "name": "Wompou",
    "lat": 15.176,
    "lon": -12.688,
    "type": "بلدية",
    "wilaya": "كيدماغا",
    "moughataa": "Wompou",
    "id": "MR01319",
    "source": "open-admin-data"
  },
  {
    "city": "Agoueinitt",
    "name": "Agoueinitt",
    "lat": 15.578,
    "lon": -12.409,
    "type": "بلدية",
    "wilaya": "كيدماغا",
    "moughataa": "Wompou",
    "id": "MR01320",
    "source": "open-admin-data"
  },
  {
    "city": "Ejar",
    "name": "Ejar",
    "lat": 15.504,
    "lon": -12.497,
    "type": "بلدية",
    "wilaya": "كيدماغا",
    "moughataa": "Wompou",
    "id": "MR01321",
    "source": "open-admin-data"
  },
  {
    "city": "Sagne Dieri",
    "name": "Sagne Dieri",
    "lat": 15.154,
    "lon": -12.527,
    "type": "بلدية",
    "wilaya": "كيدماغا",
    "moughataa": "Wompou",
    "id": "MR01322",
    "source": "open-admin-data"
  },
  {
    "city": "Arr",
    "name": "Arr",
    "lat": 15.366,
    "lon": -12.476,
    "type": "بلدية",
    "wilaya": "كيدماغا",
    "moughataa": "Wompou",
    "id": "MR01323",
    "source": "open-admin-data"
  },
  {
    "city": "Birmoughrein",
    "name": "Birmoughrein",
    "lat": 26.152,
    "lon": -7.684,
    "type": "بلدية",
    "wilaya": "تيرس زمور",
    "moughataa": "Bir Moughrein",
    "id": "MR01324",
    "source": "open-admin-data"
  },
  {
    "city": "F'Deirick",
    "name": "F'Deirick",
    "lat": 23.175,
    "lon": -10.521,
    "type": "بلدية",
    "wilaya": "تيرس زمور",
    "moughataa": "F'Deirick",
    "id": "MR01325",
    "source": "open-admin-data"
  },
  {
    "city": "Zoueirat",
    "name": "Zoueirat",
    "lat": 22.726,
    "lon": -12.353,
    "type": "بلدية",
    "wilaya": "تيرس زمور",
    "moughataa": "Zoueirat",
    "id": "MR01326",
    "source": "open-admin-data"
  },
  {
    "city": "Akjoujt",
    "name": "Akjoujt",
    "lat": 19.906,
    "lon": -14.241,
    "type": "بلدية",
    "wilaya": "انشيري",
    "moughataa": "Akjoujt",
    "id": "MR01327",
    "source": "open-admin-data"
  },
  {
    "city": "Bennechab",
    "name": "Bennechab",
    "lat": 19.84,
    "lon": -15.004,
    "type": "بلدية",
    "wilaya": "انشيري",
    "moughataa": "Bennechab",
    "id": "MR01328",
    "source": "open-admin-data"
  },
  {
    "city": "Mheijrat",
    "name": "Mheijrat",
    "lat": 18.81,
    "lon": -15.838,
    "type": "بلدية",
    "wilaya": "انشيري",
    "moughataa": "Bennechab",
    "id": "MR01329",
    "source": "open-admin-data"
  },
  {
    "city": "Ksar",
    "name": "Ksar",
    "lat": 18.33,
    "lon": -15.931,
    "type": "بلدية",
    "wilaya": "نواكشوط الغربية",
    "moughataa": "Ksar",
    "id": "MR01330",
    "source": "open-admin-data"
  },
  {
    "city": "Tefragh Zeina",
    "name": "Tefragh Zeina",
    "lat": 18.3,
    "lon": -16.016,
    "type": "بلدية",
    "wilaya": "نواكشوط الغربية",
    "moughataa": "Tevragh Zeina",
    "id": "MR01331",
    "source": "open-admin-data"
  },
  {
    "city": "Sebkha",
    "name": "Sebkha",
    "lat": 18.077,
    "lon": -16.008,
    "type": "بلدية",
    "wilaya": "نواكشوط الغربية",
    "moughataa": "Sebkha",
    "id": "MR01332",
    "source": "open-admin-data"
  },
  {
    "city": "Teyaret",
    "name": "Teyaret",
    "lat": 18.171,
    "lon": -15.929,
    "type": "بلدية",
    "wilaya": "نواكشوط الشمالية",
    "moughataa": "Toujounine",
    "id": "MR01333",
    "source": "open-admin-data"
  },
  {
    "city": "Dar Naim",
    "name": "Dar Naim",
    "lat": 18.122,
    "lon": -15.912,
    "type": "بلدية",
    "wilaya": "نواكشوط الشمالية",
    "moughataa": "Dar Naïm",
    "id": "MR01334",
    "source": "open-admin-data"
  },
  {
    "city": "Toujounine",
    "name": "Toujounine",
    "lat": 18.067,
    "lon": -15.888,
    "type": "بلدية",
    "wilaya": "نواكشوط الشمالية",
    "moughataa": "Teyarett",
    "id": "MR01335",
    "source": "open-admin-data"
  },
  {
    "city": "El Mina",
    "name": "El Mina",
    "lat": 17.946,
    "lon": -16.005,
    "type": "بلدية",
    "wilaya": "نواكشوط الجنوبية",
    "moughataa": "El Mina",
    "id": "MR01336",
    "source": "open-admin-data"
  },
  {
    "city": "Arafat",
    "name": "Arafat",
    "lat": 18.054,
    "lon": -15.959,
    "type": "بلدية",
    "wilaya": "نواكشوط الجنوبية",
    "moughataa": "Arafat",
    "id": "MR01337",
    "source": "open-admin-data"
  },
  {
    "city": "Riyad",
    "name": "Riyad",
    "lat": 17.971,
    "lon": -15.908,
    "type": "بلدية",
    "wilaya": "نواكشوط الجنوبية",
    "moughataa": "Riad",
    "id": "MR01338",
    "source": "open-admin-data"
  }
];

export const mauritaniaCommunes = Object.fromEntries(
  mauritaniaCommunesList.map((commune) => [
    commune.city,
    {
      lat: commune.lat,
      lon: commune.lon,
      name: arName(commune),
      nameEn: commune.name,
      type: commune.type,
      wilaya: normalizeMauritaniaWilayaName(commune.wilaya),
      moughataa: normalizeMauritaniaMoughataaName(commune.moughataa),
      id: commune.id,
      source: commune.source,
    },
  ])
);

export const mauritaniaCommuneDistricts = mauritaniaCommunesList.map((commune) => ({
  name: arName(commune),
  nameEn: commune.name,
  cityKey: commune.city,
  lat: commune.lat,
  lon: commune.lon,
}));

export const mauritaniaAdministrativeWilayas = [
  ...new Set(
    mauritaniaCommunesList
      .map((commune) => normalizeMauritaniaWilayaName(commune.wilaya))
      .filter(Boolean)
  ),
].sort((a, b) => a.localeCompare(b, 'ar'));

export const mauritaniaAdministrativeMoughataas = [
  ...new Set(
    mauritaniaCommunesList
      .map((commune) => normalizeMauritaniaMoughataaName(commune.moughataa))
      .filter(Boolean)
  ),
].sort((a, b) => a.localeCompare(b, 'ar'));

export const mauritaniaAdministrativeCounts = {
  wilayas: mauritaniaAdministrativeWilayas.length,
  moughataas: mauritaniaAdministrativeMoughataas.length,
  communes: mauritaniaCommunesList.length,
};
